version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Deploy to Render
          command: |
            curl -X POST https://api.render.com/deploy/srv-xxxxxxxxxxxx?key=your_deploy_hook_key

workflows:
  version: 2
  deploy_on_push:
    jobs:
      - build-and-deploy
